### PR TITLE
Fix #80

### LINKED ISSUE #80: Raise application window when clicked on notification
**Description**
When a new message comes and the notification appears, after clicking nothing happens.

**To Reproduce**
1. Get a new message.
2. Click the notification.

**Expected behavior**
After clicking the application should open that message or at least the app.

**Environment**
 - Ubuntu 20.04.1
 - Deb package

### PR DESCRIPTION
**Pull request by GlowingScrewdriver**
Fixes #80 (Raise application window when clicked on notification)

Deals with the situation when the app is minimised to the tray (i.e,
has no windows). The desired behaviour is already displayed well
enough when the app has a window.

Tested on Cinnamon 5.0.6, Debian 12 "Bookworm".

### CODE REVIEW

File: src/ui/MainWindow.cpp [hunk 1]
```diff
@@ -83,6 +83,7 @@ namespace wfl::ui
 
         m_webView.signalLoadStatus().connect(sigc::mem_fun(*this, &MainWindow::onLoadStatusChanged));
         m_webView.signalNotification().connect(sigc::mem_fun(m_trayIcon, &TrayIcon::setAttention));
+        m_webView.signalNotificationClicked().connect(sigc::mem_fun(*this, &MainWindow::onNotificationClicked));
```
Comment (eneshecan) [inline src/ui/MainWindow.cpp:86]: You can directly use the `onShow` function to avoid duplicate code and implement a more reliable mechanism.

File: src/ui/WebView.cpp [hunk 2]
```diff
@@ -134,7 +142,7 @@ namespace wfl::ui
                 webView->signalNotification().emit(true);
             }
 
-            g_signal_connect(notification, "clicked", G_CALLBACK(notificationDestroyed), webView);
```
Comment (eneshecan) [inline src/ui/WebView.cpp:137]: I remember that this line is intended to make tray icon normal again when the notification is clicked. Please check that if notifying `closed` covers clicking as well by checking whether the tray icon goes back to normal state when you click on a notification, otherwise keep this line.

**Review by eneshecan — COMMENTED** [review]
Thanks for the nice work! I requested some changes.

File: src/ui/MainWindow.cpp (hunk 1 above)
Comment (GlowingScrewdriver) [reply src/ui/MainWindow.cpp:86]: If I use `onShow`, and there are no windows, a new window is created, but isn't actually displayed -- it doesn't come to the foreground. Apparently `show` only "[flags a widget to be displayed](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Widget.html#Gtk.Widget.show)". However, if I change `show` to `present` in `onShow`, it works. Shall I do that?

```C++
    void MainWindow::onShow()
    {
        if (!is_visible())
        {
            Application::getInstance().add_window(*this);
            // This is the line I'm suggesting we change
            // show();
            present();
        }
        else
        {
            present();
        }
    }
```

File: src/ui/WebView.cpp (hunk 2 above)
Comment (GlowingScrewdriver) [reply src/ui/WebView.cpp:137]: Yes. I can confirm that when the notification arrives, the icon gets a red dot; and when the notification is clicked, the red dot goes away.

Even previously, when a notification arrived and the window was manually opened by the user without interaction with the notification, the red dot would go away. I suppose that is what takes care of this issue you brought to light.

File: src/ui/MainWindow.cpp (hunk 1 above)
Comment (eneshecan) [reply src/ui/MainWindow.cpp:86]: I see. Okay then, let's do it as you say. However, a bit of code improvement would be:
```cpp
if (!is_visible())
{
    Application::getInstance().add_window(*this);
}

present();
```

Comment (GlowingScrewdriver) [reply src/ui/MainWindow.cpp:86]: Ah, yes. I should have seen that.

Alright, I'll go ahead and make the changes.
