### PR TITLE
alters attention tray icon to normal when on show main window

### LINKED ISSUE #155: The tray icon always shows as if a message has arrived
**Description**
The tray icon always shows as if a message has arrived. This can be seen by the tray icon immediately when the application is loaded (being logged in).

**To Reproduce**
1. Launch the application
2. Maybe it's because of the new "BETA" mode enabled
3. Look in the tray

**Expected behavior**
I expected that after reading all the messages, the tray icon would just be green. And when messages arrive, either an unread message counter or a red dot will be displayed on the icon.

**Screenshots**
изображение

**Environment**
- Kernel: 5.15.12-1-MANJARO x86_64 
- bits: 64 
- compiler: gcc v: 11.1.0
- Desktop: Xfce 4.16.0 
- Distro: Manjaro Linux 
- base: Arch Linux

### PR DESCRIPTION
**Pull request by berkeyvx**
Fixes #155

### CODE REVIEW

File: src/ui/MainWindow.cpp [hunk 1]
```diff
@@ -213,10 +213,19 @@ namespace wfl::ui
         }
     }
 
+    void MainWindow::onNotificationReceived(bool attention)
+    {
+        if(!is_visible())
```
Comment (eneshecan) [inline src/ui/MainWindow.cpp:218]: Please put a space between `if` and statement `(...)`

File: src/ui/MainWindow.cpp [hunk 2]
```diff
@@ -213,10 +213,19 @@ namespace wfl::ui
         }
     }
 
+    void MainWindow::onNotificationReceived(bool attention)
```
Comment (eneshecan) [inline src/ui/MainWindow.cpp:216]: Please change the function signature to `onNotificationChanged` since the signal notifies the status of notification (whether in a notified state or not)

**Review by eneshecan — CHANGES_REQUESTED** [review]
Thanks for this! The implementation and logic look good to me other than some small things I commented.
